version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
    ports:
     - "26001:27017"
    volumes:
     - catalog_mongo_data:/data/db

  basket.db:
    container_name: basket.db
    ports:
     - "26002:6379"
    volumes:
     - basket_redis_data:/data

  discount.db:
    container_name: discount.db
    environment:
     - POSTGRES_USER=discount.api
     - POSTGRES_PASSWORD=DisC0unt.Ap1@pass
     - POSTGRES_DB=Discount
    ports:
     - "26003:5432"
    volumes:
     - discount_postgres_data:/var/lib/postgresql/data
     
  #portainer:
  #  container_name: portainer
  #  ports:
  #   - "8000:8000"
  #   - "9000:9000"
  #  volumes:
  #   - portainer_data:/data
  #   - /var/run/docker.sock:/var/run/docker.sock

  catalog.api:
    container_name: catalog.api
    ports:
      - "10001:80"

  basket.api:
    container_name: basket.api
    ports:
      - "10002:80"

  discount.api:
    container_name: discount.api
    ports:
      - "10003:80"

  discount.grpc:
    container_name: discount.grpc
    ports:
      - "10004:80"
