version: '3.4'

services:
  catalog.db:
    ports:
     - "26001:27017"
    volumes:
     - catalog_mongo_data:/data/db

  basket.db:
    ports:
     - "26002:6379"
    volumes:
     - basket_redis_data:/data

  discount.db:
    environment:
     - POSTGRES_USER=discount.api
     - POSTGRES_PASSWORD=DisC0unt.Ap1@pass
     - POSTGRES_DB=Discount
    ports:
     - "26003:5432"
    volumes:
     - discount_postgres_data:/var/lib/postgresql/data
     
  ordering.db:
    environment:
     - "SA_PASSWORD=Your_password123"
    ports:
     - "26004:1433"

  rabbitmq:
    ports:
      - "11003:5672"  # RabbitMq Broker
      - "11004:15672" # RabbitMq Management Portal

  #portainer:
  #  container_name: portainer
  #  ports:
  #   - "11001:8000"
  #   - "11002:9000"
  #  volumes:
  #   - portainer_data:/data
  #   - /var/run/docker.sock:/var/run/docker.sock

  catalog.api:
    ports:
      - "10001:80"

  basket.api:
    ports:
      - "10002:80"

  discount.api:
    ports:
      - "10003:80"

  discount.grpc:
    ports:
      - "10004:80"

  ordering.api:
    ports:
      - "10005:80"
