version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
#    restart: always
    ports:
     - "26001:27017"
    volumes:
     - catalog_mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoSettings:ConnectionString=mongodb://catalog.db:27017"
    depends_on:
      - catalog.db
    ports:
      - "10001:80"
